[LA-2314] reusable workflow for format& run unit test for golang projects
spring-media/la-shared-github-workflows pull request #23
Opened 2023-05-04 12:32 UTC by FatmaTosun

## What does this change?

create reusable workflow for format and run unit test for golang projects

## Why?

## Link to supporting ticket or Screenshots (if applicable)

2023-05-04 12:40 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__format-unit-test.yml
> +      GO_VERSION:
I prefer to pass `GO_VERSION` in case we want to upgrade version in our projects.

2023-05-05 07:49 UTC, k-pusch reviewed
I have some small questions. Otherwise it looks pretty straight forward to me.

2023-05-05 07:49 UTC, k-pusch commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +        required: true
Do we have a "standard" default go version we could use as a default? and just overwrite it when we need a specific go version?

2023-05-05 07:49 UTC, k-pusch commented on README.md
> +      GOLANG_VERSION: ${{ secrets.GO_VERSION }}
I am not sure if we want to have the GO_VERSION as a github secret, or? Usually we set all the secrets in la-hollywood and those are mostly just keys and passwords. Why not passing it in as a string/number value? 

Or am i missing something? Just wondering if this documentation would lead to confusion.

2023-05-05 08:06 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +        required: true
I would always be explicit here. Less magic.

2023-05-05 08:08 UTC, nhoffmann commented on README.md
> +      GOLANG_VERSION: ${{ secrets.GO_VERSION }}
True. It is misleading. It is highly unlikely the version will come from a Github secret.

2023-05-05 08:11 UTC, nhoffmann commented on README.md
> +      GOLANG_VERSION: ${{ secrets.GO_VERSION }}
I think we can make this more clear by making the GOLANG_VERSION an input to the shared workflow instead of a secret. It is technically the same, but semantically more clear.

https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

2023-05-05 08:11 UTC, k-pusch commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +        required: true
Fair point

2023-05-05 08:12 UTC, FatmaTosun commented on README.md
> +      GOLANG_VERSION: ${{ secrets.GO_VERSION }}
true, I will pass it as input.

2023-05-05 08:15 UTC, FatmaTosun commented on README.md
> +      GOLANG_VERSION: ${{ secrets.GO_VERSION }}
done.

2023-05-05 08:18 UTC, nhoffmann commented on README.md
> +      GOLANG_VERSION: ${{ secrets.GO_VERSION }}
The readme needs adjusting too 😇

2023-05-05 09:13 UTC, nhoffmann requested changes
Some suggestions on how to make this even better and clearer.

2023-05-05 09:13 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          git config --global url."https://${{ secrets.LA_TECH_USER_AUTH_TOKEN }}:x-oauth-basic@github.com/spring-media".insteadOf "https://github.com/spring-media"
Do we really need this step for testing and formatting? If not, can we remove it? Or am I missing something?

2023-05-05 09:13 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +      - name: Check go modules cache
I think we want to adjust the step name. The name here is similar to the name of the following step that verifies whether everything is properly formatted. 
But this step here is still setup, it tries to restore go modules from a cache to speed up the setup.

I think it will avoid confusion if we make it more clear, that this is still setup and not actually running a check on the codebase.

2023-05-05 09:13 UTC, nhoffmann commented on README.md
> +The [golang\_\_format-unit-tests workflow](./.github/workflows/reusable-workflow__golang__format-unit-tests.yml) will set up golang version and format & run unit tests on the project:
Maybe nitpicky, but I would make it clear that it does not format anything, it checks whether everything is formatted properly and errors otherwise, right?

2023-05-05 09:16 UTC, FatmaTosun commented on README.md
> +The [golang\_\_format-unit-tests workflow](./.github/workflows/reusable-workflow__golang__format-unit-tests.yml) will set up golang version and format & run unit tests on the project:
yes, that's true. I will make it clearer `will set up golang version and check formatted properly and run unit tests on the project `

2023-05-05 12:52 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          git config --global url."https://${{ secrets.LA_TECH_USER_AUTH_TOKEN }}:x-oauth-basic@github.com/spring-media".insteadOf "https://github.com/spring-media"
we need pull dependencies we can't remove it.

2023-05-05 14:03 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          git config --global url."https://${{ secrets.LA_TECH_USER_AUTH_TOKEN }}:x-oauth-basic@github.com/spring-media".insteadOf "https://github.com/spring-media"
It's not related being shared-workflow or not we need it for running unit tests. Our unit tests are not completely mocked so we need to pull dependencies. For example;

https://github.com/spring-media/la-hua-api/blob/main/internal/api/utils_unit_test.go#L23

we do call `profile.NewMockedUserProfileClient` so we need to have `"github.com/spring-media/la-golang-shared/profile"` . If it's not already cached we have to pull it.

2023-05-05 14:44 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          git config --global url."https://${{ secrets.LA_TECH_USER_AUTH_TOKEN }}:x-oauth-basic@github.com/spring-media".insteadOf "https://github.com/spring-media"
Ok, so it's not a direct dependency. We only need it in some projects because when running tests, we might need to pull in dependencies that are only available in private Github repositories. 

Since that all is not obvious from looking at the workflow, can we put this information into the shared workflow? As a comment maybe?

2023-05-05 14:58 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          git config --global url."https://${{ secrets.LA_TECH_USER_AUTH_TOKEN }}:x-oauth-basic@github.com/spring-media".insteadOf "https://github.com/spring-media"
sure, I will add comment.

2023-05-05 15:01 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          git config --global url."https://${{ secrets.LA_TECH_USER_AUTH_TOKEN }}:x-oauth-basic@github.com/spring-media".insteadOf "https://github.com/spring-media"
added.

2023-05-05 15:12 UTC, nhoffmann approved these changes
Looks good to me. 
We can only know if everything is in order by running it though. This is Github Actions, something one always forgets. You could test it by pointing one of the PRs that are already open to start using it against the latest git commit of this branch. Or maybe you did that already.

2023-05-05 15:12 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          git config --global url."https://${{ secrets.LA_TECH_USER_AUTH_TOKEN }}:x-oauth-basic@github.com/spring-media".insteadOf "https://github.com/spring-media"
Thanks! I think this will our future selfs in understanding this.

2023-05-05 15:57 UTC, FatmaTosun commented
> Looks good to me.
> We can only know if everything is in order by running it though. This is Github Actions, something one always forgets. You could test it by pointing one of the PRs that are already open to start using it against the latest git commit of this branch. Or maybe you did that already.

Actually, I didn't :/ After your comment I tested interactive-api against latest commit and I realised we can not reference secrets directly. https://github.com/spring-media/la-shared-github-workflows/pull/23/commits/9bd26fb1ee6fc7be81f709bd509cc814da195ed9 Thank you 🙏

2023-05-08 07:10 UTC, nhoffmann requested changes
I am against pulling the bouncer key into this shared workflow. It is mixing concerns, which will lead to confusion.

2023-05-08 07:10 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          chmod 600 resources/bouncer_private.pem
This introduces a bit too much magic for my taste. I think this should go into the workflow that needs the private key. The reason would be to make it more clear in the project where that pem is coming from, where it is defined. It is hard to follow when a shared workflow that is about. This also has nothing to do with linting and unit testing.

2023-05-08 07:13 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          fi
Can you elaborate why we need to have this in the shared workflow?
This introduces a bit too much magic for my taste. I really think this should go into the workflow that needs the private key. The reason would be to make it more clear in the project, where that pem is coming from, where it is defined. It is hard to follow when it is coming from a shared workflow that is about unit tests. This has nothing to do with linting and unit testing.

2023-05-08 07:15 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          fi
Do we need that bouncer_private.pem to be present to run the tests?

2023-05-11 08:47 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          fi
This private key defined in secrets and it is needed for generating jwt token with casinoClient. We have 2 endpoints that generate code with this private key.

`/qrcode/validate`
`/qrcode/initValidation`

About why we need to have this in shared workflow, because we have unit test for `/qrcode/validate`(TestValidateEndpoint) and it's not completely mocked. But I can mock encodeCode part and remove this `Copy bouncer private key` step from here.

2023-05-11 08:59 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          fi
IIUC we only need this for la-bouncer-apis workflow. I was just wondering if we can move it to that project and not have it in the shared library. 

I would really prefer not using the shared workflow for bouncer-api then, instead of hacking something in here temporarily. We can start using the shared workflow for bouncer-api, when we removed casino from bouncer-api entirely.

2023-05-11 10:07 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__format-unit-tests.yml
> +          fi
yes, that's correct we only need for la-bouncer-api. 

I will remove it from workflow then.

2023-05-11 10:17 UTC, nhoffmann approved these changes
Very nice!

2023-05-11 10:20 UTC, nhoffmann commented
@FatmaTosun You probably know it but here's a reminder anyway: After merging the branch we need to release a new minor version and update the tag as described here https://github.com/spring-media/la-shared-github-workflows#releasing

2023-05-11 11:38 UTC, merged