pass check-snyk-input
spring-media/la-shared-github-workflows pull request #28
Opened 2023-05-23 11:56 UTC by FatmaTosun

## What does this change?

- add `check-snyk` as input to run `synk test` 
- update readme

## Why?

make `run synk test` optional.

## Link to supporting ticket or Screenshots (if applicable)

2023-05-24 15:19 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
I would like to discuss the defaults here. Why do we need to make running the snyk action configurable in the first place? At least I would think we want it to be `true` by default, so we give the opportunity to opt out, but force people to make that a conscious decision.
But maybe I am missing something, what is the reason for setting this to false by default?

2023-05-24 15:22 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
And a comment about the `severity-threshold` input. Can we make it clear in the name already, that that is about the snyk action? Maybe name it `snyk-severity-threshold`?
And I really think we want the default to be `critical` there. Like we discussed in the last Team JF, we are currently only interested in `critical` vulnerabilities. We can change that in the future, but I think it would be good to start with something that doesn't possibly trigger on every PR.

2023-05-24 15:28 UTC, nhoffmann commented on .github/workflows/reusable-workflow__js__security.yml
> +        default: false
Same here, I think this should default to true.

2023-05-24 15:30 UTC, nhoffmann commented on README.md
> +      severity-threshold: <vulnerabilities threshold not required and default value is low>
I think we need to update the default here, at least it's not `low` by default.

2023-05-25 12:09 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__security.yml
> -        continue-on-error: true
`continue-on-error` default is false, action will stop when it encounters a security vulnerability. https://github.com/snyk/actions

2023-05-25 12:19 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
Base on our discussion [here](https://spring-media.slack.com/archives/CLJ0JRCAD/p1684767443861609?thread_ts=1684766432.042689&cid=CLJ0JRCAD) I thought we want to make it configurable, did I understand wrong? 

If I understand wrong we just want to pass even there is error, `snyk` allows us to do that by passing `continue-on-error=true`

> I would like to discuss the defaults here. Why do we need to make running the snyk action configurable in the first place? At least I would think we want it to be `true` by default, so we give the opportunity to opt out, but force people to make that a conscious decision.
> 
> But maybe I am missing something, what is the reason for setting this to false by default?

2023-05-25 13:47 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
Wait, IIUC `continue-on-error=true` is something completely different. 
With the `check-snyk` input you are not letting the action pass, it effectively does not run snyk at all, when it is set to false.

2023-05-25 13:49 UTC, nhoffmann commented on .github/workflows/reusable-workflow__js__security.yml
> +        default: false
>we want to make run  synk test optional or do we want to stop the action optional if it fails

I don't understand. To me those are very different things.

2023-05-25 13:56 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
Are you referring to this?

> We don't have to make passing the Snyk check mandatory yet. We can make it more restrictive later.

What I meant was, that in the branch protection rules on Github, we do not have to add the security action a check that is required to pass before we can merge a PR into the default branch. We want it to warn us about security problems, but we don't want it to prevent us from merging, as these vulnerabilities are not always simple to resolve.

I still wouldn't know when we want to disable the snyk action, I definitely think it should be switched on by default.

2023-05-26 10:17 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
yes, when `check-snyk` is set false it does not run snyk at all.
> With the `check-snyk` input you are not letting the action pass, it effectively does not run snyk at all, when it is set to false.

2023-05-26 10:25 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
> What I meant was, that in the branch protection rules on Github, we do not have to add the security action a check that is required to pass before we can merge a PR into the default branch. We want it to warn us about security problems, but we don't want it to prevent us from merging, as these vulnerabilities are not always simple to resolve.

When we run `synk test` it returns error if vulnerabilities are detected, so we can not bypass without fixing vulnerabilities.
```
The snyk test command scans your project, tests dependencies for vulnerabilities, and reports how many vulnerabilities are found.
The command returns a non-zero exit code which causes a build to fail when run inside of CI environments (depending on how the CI tool is configured).
```


> I still wouldn't know when we want to disable the snyk action, I definitely think it should be switched on by default.

Now default value is true.

2023-05-26 10:37 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
Yes, that is what we want. It should show us that the snyk action failed. And then the whole security actions fails. 

We don't have to bypass it. And we do not have to fix the vulnerability unless we explicitly say in the Github project
that passing the security action is a requirement for being able to merge a PR. This is being configured via branch protection rules. We have full control over that. It's just we do not configure that kind of thing in the action itself.

2023-05-26 10:47 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
I would still vote for taking this check out entirely. It seems YAGNI at the moment. We can add it when we actually need something like this.

2023-05-26 10:47 UTC, nhoffmann commented on .github/workflows/reusable-workflow__golang__security.yml
> -        continue-on-error: true
Can you put the `continue-on-error: true` back in then?

2023-05-26 10:47 UTC, nhoffmann commented on README.md
> +Rquired secrets
```suggestion
Required secrets
```

2023-05-26 10:49 UTC, nhoffmann reviewed
Another question, did you include this action somewhere already for testing purposes? It would be great to see it in action.

2023-05-26 10:57 UTC, nhoffmann requested changes
And another question: The js action installs dependencies. The golang action installs dependencies, sets up AWS, sets up the ability to checkout other repositories. 

I was under the impression that the `snyk test` command performs a static code analysis. 
Also, when looking at the examples on the [snyk action repo](https://github.com/snyk/actions) I don't see any examples that installs dependencies either.

Are we totally sure we need to install the dependencies and do all this setup?

2023-05-31 14:21 UTC, FatmaTosun commented on .github/workflows/reusable-workflow__golang__security.yml
> +        default: false
We talked offline we don't want to make `run snyk test` optional. Repositories would decide to make this workflow required or not. Besides we will only be notified for critical which we want fix. https://github.com/spring-media/la-shared-github-workflows/pull/31/files

2023-05-31 14:21 UTC, closed without merging