adding pipeline permissions
spring-media/la-shared-github-workflows pull request #42
Opened 2024-07-11 15:04 UTC by sergeychernyshov-code

## What does this change?
changes credentials to oidc instead of aws keys, in this PR we are adding exclusive pipeline permissions needed for OIDC

## Why?
Pipelines with OIDC require defined set of permissions

## Link to supporting ticket or Screenshots (if applicable)
https://axelspringer.atlassian.net/browse/LA-442

2024-07-11 15:58 UTC, k-pusch requested changes

2024-07-11 15:58 UTC, k-pusch commented on README.md
> +For authentication to AWS this job uses OIDC instead of plain IAM credential keys.
Please add a note that this change got introcuded in version 3.

2024-07-11 15:58 UTC, k-pusch commented on README.md
>      uses: spring-media/la-shared-github-workflows/.github/workflows/reusable-workflow__aws-remove-bucket.yaml@v1
```suggestion
    uses: spring-media/la-shared-github-workflows/.github/workflows/reusable-workflow__aws-remove-bucket.yaml@v3
```

2024-07-11 15:58 UTC, k-pusch commented on README.md
>      uses: spring-media/la-shared-github-workflows/.github/workflows/reusable-workflow__aws-remove-bucket.yaml@v1
Unfortnuately i only can make the suggestion here. But in all the comments we would need to update it to v3 for easier usage in future.

2024-07-17 15:14 UTC, sergeychernyshov-code commented on README.md
> +For authentication to AWS this job uses OIDC instead of plain IAM credential keys.
added a hint that workflows should use v3

2024-07-22 06:39 UTC, k-pusch requested changes
We still have a bunch of 

spring-media/la-shared-github-workflows/.github/workflows/reusable-workflow__js__deploy-to-s3.yaml@v1

in the documentation, please check again and update everything to v3

2024-07-22 06:39 UTC, k-pusch commented on README.md
>        build_script_name: <the npm script to build the project>
Above again: @v3 instead of v1 please

2024-07-22 07:37 UTC, k-pusch requested changes

2024-07-22 07:37 UTC, k-pusch commented on README.md
> +
Something is off with the MARKDOWN syntax here. 

The part ###Workflows should not be part of the yaml code.
If you look at this README file something is off.

https://github.com/spring-media/la-shared-github-workflows/blob/17f7a87848b33929468ed5a9a218d8054eae6fe0/README.md

2024-07-22 10:11 UTC, k-pusch approved these changes

2024-07-22 10:12 UTC, merged